TYPE=VIEW
query=select `db_bbsystem`.`tb_loanbook`.`loanbook_id` AS `loanbook_id`,`db_bbsystem`.`tb_loanbook`.`accession_no` AS `accession_no`,`db_bbsystem`.`tb_loanbook`.`due_date` AS `due_date`,`db_bbsystem`.`tb_loanbook`.`date_return` AS `date_return`,`db_bbsystem`.`tb_loanbook`.`time_return` AS `time_return`,`tb_loanpatron`.`loan_id` AS `loan_id`,`tb_loanpatron`.`stf_id` AS `stf_id`,`tb_loanpatron`.`library_id` AS `library_id`,`tb_loanpatron`.`release_date` AS `release_date`,`tb_loanpatron`.`release_time` AS `release_time`,`tb_loanpatron`.`patron_fname` AS `patron_fname`,`tb_loanpatron`.`patron_mname` AS `patron_mname`,`tb_loanpatron`.`patron_lname` AS `patron_lname`,`tb_loanpatron`.`stf_fname` AS `stf_fname`,`tb_loanpatron`.`stf_mname` AS `stf_mname`,`tb_loanpatron`.`stf_lname` AS `stf_lname`,`tb_bookrecords`.`title` AS `title`,`tb_bookrecords`.`edition` AS `edition`,`tb_bookrecords`.`isbn` AS `isbn`,`tb_bookrecords`.`material_type` AS `material_type`,`tb_bookrecords`.`copyright` AS `copyright`,`tb_bookrecords`.`place_publisher` AS `place_publisher`,`tb_bookrecords`.`pages` AS `pages`,`tb_bookrecords`.`price` AS `price`,`tb_bookrecords`.`images` AS `images`,`tb_bookrecords`.`author` AS `author`,`tb_bookrecords`.`book_id` AS `book_id`,`tb_bookrecords`.`call_no` AS `call_no`,`tb_bookrecords`.`copy_number` AS `copy_number`,`tb_bookrecords`.`location` AS `location`,`tb_bookrecords`.`funding_source` AS `funding_source`,`tb_bookrecords`.`status` AS `status` from `db_bbsystem`.`tb_bookrecords` join `db_bbsystem`.`tb_loanpatron` join `db_bbsystem`.`tb_loanbook` where ((`tb_bookrecords`.`accession_no` = `db_bbsystem`.`tb_loanbook`.`accession_no`) and (`db_bbsystem`.`tb_loanbook`.`loan_id` = `tb_loanpatron`.`loan_id`))
md5=58b1503275119d212cc1bc11c068ff1d
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
revision=1
timestamp=2020-12-26 22:04:29
create-version=1
source=SELECT \n  `tb_loanbook`.`loanbook_id`,\n  `tb_loanbook`.`accession_no`,\n  `tb_loanbook`.`due_date`,\n  `tb_loanbook`.`date_return`,\n  `tb_loanbook`.`time_return`,\n  `tb_loanpatron`.`loan_id`,\n  `tb_loanpatron`.`stf_id`,\n  `tb_loanpatron`.`library_id`,\n  `tb_loanpatron`.`release_date`,\n  `tb_loanpatron`.`release_time`,\n  `tb_loanpatron`.`patron_fname`,\n  `tb_loanpatron`.`patron_mname`,\n  `tb_loanpatron`.`patron_lname`,\n  `tb_loanpatron`.`stf_fname`,\n  `tb_loanpatron`.`stf_mname`,\n  `tb_loanpatron`.`stf_lname`,\n  `tb_bookrecords`.`title`,\n  `tb_bookrecords`.`edition`,\n  `tb_bookrecords`.`isbn`,\n  `tb_bookrecords`.`material_type`,\n  `tb_bookrecords`.`copyright`,\n  `tb_bookrecords`.`place_publisher`,\n  `tb_bookrecords`.`pages`,\n  `tb_bookrecords`.`price`,\n  `tb_bookrecords`.`images`,\n  `tb_bookrecords`.`author`,\n  `tb_bookrecords`.`book_id`,\n  `tb_bookrecords`.`call_no`,\n  `tb_bookrecords`.`copy_number`,\n  `tb_bookrecords`.`location`,\n  `tb_bookrecords`.`funding_source`,\n  `tb_bookrecords`.`status`\nFROM\n  `tb_bookrecords`,\n  `tb_loanpatron`,\n  `tb_loanbook`\nWHERE\n  `tb_bookrecords`.`accession_no` = `tb_loanbook`.`accession_no` AND \n  `tb_loanbook`.`loan_id` = `tb_loanpatron`.`loan_id`
